name: lss
channels:
  - conda-forge
dependencies:
  - python
  - boost
  - cython
  - fitsio
  - gcc
  - gsl
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - git
  - ipython
  - jupyter
  - joblib
